# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-5.2.2
apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.podman.annotations.kube.health.check/dmarc-visualizer-elasticsearch: "true"
    io.podman.annotations.kube.health.check/dmarc-visualizer-grafana: "true"
    io.podman.annotations.kube.health.check/dmarc-visualizer-parsedmarc: "true"
  creationTimestamp: "2025-01-11T11:45:28Z"
  labels:
    app: dmarc-visualizer
  name: dmarc-visualizer
spec:
  initContainers:
  containers:
    - args:
        - eswrapper
      env:
        - name: TERM
          value: xterm
        - name: discovery.type
          value: single-node
      image: docker.elastic.co/elasticsearch/elasticsearch:sha256-fefc5c834958f142371b0f64b6cbd77e00c3d53c83f87842e7cd17ce2fd1fa87
      name: elasticsearch
      securityContext: {}
      tty: true
      volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: elasticsearch-data
    - args:
        - /usr/local/bin/parsedmarc
        - -c
        - /parsedmarc.ini
        - /input/*
        - --debug
      env:
        - name: TERM
          value: xterm
      image: localhost/parsedmarc:latest
      name: parsedmarc
      securityContext: {}
      tty: true
      volumeMounts:
        - mountPath: /input
          name: parsedmarc-input
          readonly: true
        - mountPath: /output
          name: parsedmarc-output
    - env:
        - name: TERM
          value: xterm
        - name: GF_INSTALL_PLUGINS
          value: grafana-piechart-panel,grafana-worldmap-panel
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "true"
      image: localhost/grafana:parsedmarc
      name: grafana
      ports:
        - containerPort: 3000
          hostPort: 3000
      securityContext:
        runAsNonRoot: true
      tty: true
  restartPolicy: Always
  volumes:
    - hostPath:
        path: /opt/dmarc-visualizer/elasticsearch/data
        type: Directory
      name: elasticsearch-data
    - hostPath:
        path: /opt/dmarc-visualizer/parsedmarc/input
        type: Directory
      name: parsedmarc-input
    - hostPath:
        path: /opt/dmarc-visualizer/parsedmarc/output
        type: Directory
      name: parsedmarc-output
